"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import environ
from datetime import timedelta
from pathlib import Path

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"])
)

BASE_DIR = Path(__file__).resolve().parent.parent

# Читаем .env файл, если он есть (полезно для локальной разработки без Docker)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
ANGULAR_DIR = BASE_DIR.parent / "frontend/dist/frontend/browser"

# --- СЕКЦИЯ БЕЗОПАСНОСТИ ---
SECRET_KEY = env('SECRET_KEY', default='your-fallback-secret-key')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# --- БАЗА ДАННЫХ ---
# Эта строка автоматически распарсит DATABASE_URL из docker-compose
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR}/db.sqlite3')
}

# Authentication
AUTH_USER_MODEL = "users.User"
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=365),
    "AUTH_HEADER_TYPES": ("Bearer", "Token"),
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_filters",
    "users.apps.UsersConfig",
    "articles.apps.ArticlesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", ANGULAR_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# --- КОРСЫ (Важно для Angular) ---
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=["http://localhost:4200"])
CORS_URLS_REGEX = r"^/api/.*$"
# Если ты заходишь по IP (обязательно с указанием протокола)
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Если список пуст (например, при первом запуске), добавим туда все из ALLOWED_HOSTS
if not CSRF_TRUSTED_ORIGINS:
    for host in ALLOWED_HOSTS:
        if host != '*':
            CSRF_TRUSTED_ORIGINS.append(f'http://{host}')
            CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
# Для отладки в K8s можно также добавить (если проксирует на 8000 внутри)
CSRF_TRUSTED_ORIGINS += ['http://localhost:8000', 'http://backend-service:8000']

# Указываем Django доверять заголовку X-Forwarded-Proto, который ставит Nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Если ты работаешь без HTTPS (только по IP), убедись, что эти настройки в False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Доверять заголовку хоста, который передает Nginx
USE_X_FORWARDED_HOST = True
# Доверять заголовку порта
USE_X_FORWARDED_PORT = True

# Если ты не используешь HTTPS (пока что), это критично:
CSRF_COOKIE_HTTPONLY = False  # Чтобы Angular мог прочитать куку, если нужно

# --- СТАТИКА И МЕДИА ---
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles" # Сюда соберется всё для прода

# Если Angular билд лежит в корне проекта
STATICFILES_DIRS = [ANGULAR_DIR] if ANGULAR_DIR.exists() else []

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
    "EXCEPTION_HANDLER": "config.exceptions.custom_exception_handler",
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DEFAULT_RENDERER_CLASSES": [
        "config.renderers.CustomJSONRenderer",
    ],
}
