apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.backend }}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@db-service:5432/{{ .Values.postgres.db }}"
        - name: ALLOWED_HOSTS
          value: {{ .Values.backend.allowedHosts | quote }}
        - name: CSRF_TRUSTED_ORIGINS
          value: "http://{{ .Values.backend.externalIp }}"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
